# Copyright (C) 2011-2020 Aratelia Limited - Juan A. Rubio and contributors
#
# This file is part of Tizonia
#
# Tizonia is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# Tizonia is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
# more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Tizonia.  If not, see <http://www.gnu.org/licenses/>.

#
# Travis-ci configuration file (see http://travis-ci.org)
#
#

sudo: required
dist: bionic
language: c
compiler: gcc
python: 3.6
before_install:
  - ./tools/tizonia-travis-build-bionic deps "$HOME"
  - ./tools/tizonia-travis-build-bionic pydeps "$HOME"
before_script:
  - ./tools/tizonia-travis-build-bionic media "$HOME" "$HOME/temp"
script:
  - ./tools/tizonia-travis-build-bionic build "$HOME/build/tizonia/tizonia-openmax-il"
  - ./tools/tizonia-travis-build-bionic config "$HOME/build/tizonia/tizonia-openmax-il"
  - ./tools/tizonia-travis-build-bionic unit "$HOME/build/tizonia/tizonia-openmax-il"
  - ./tools/tizonia-travis-build-bionic skema "$HOME/build"
  - ./tools/tizonia-travis-build-bionic suites "$HOME/build"
after_success:
  - ./tools/tizonia-travis-build-bionic coverage "$HOME/build/tizonia/tizonia-openmax-il"
