# Travis-ci configuration file (see https://docs.travis-ci.com/)
#
# Copyright (C) 2011-2020 Aratelia Limited - Juan A. Rubio and contributors
#
# This file is part of Tizonia
#
# Tizonia is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# Tizonia is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
# more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Tizonia.  If not, see <https://www.gnu.org/licenses/>.
---
os: linux
arch: amd64
dist: bionic
version: ">= 1.0.0"

language: c
compiler: gcc
python: 3.8

jobs:
  fast_finish: true

virtualenv:
  system_site_packages: true

git:
  autocrlf: input

addons:
  apt:
    dist: bionic
    update: true

before_install:
  - ./tools/tizonia-travis-build-bionic deps "$HOME"
  - ./tools/tizonia-travis-build-bionic pydeps "$HOME"

before_script:
  - ./tools/tizonia-travis-build-bionic media "$HOME" "$HOME/temp"

script:
  - ./tools/tizonia-travis-build-bionic build "$HOME/build/tizonia/tizonia-openmax-il"
  - ./tools/tizonia-travis-build-bionic config "$HOME/build/tizonia/tizonia-openmax-il"
  - ./tools/tizonia-travis-build-bionic unit "$HOME/build/tizonia/tizonia-openmax-il"
  - ./tools/tizonia-travis-build-bionic skema "$HOME/build"
  - ./tools/tizonia-travis-build-bionic suites "$HOME/build"

after_success:
  - ./tools/tizonia-travis-build-bionic coverage "$HOME/build/tizonia/tizonia-openmax-il"
